services:
  db:
    image: mariadb:11.8.5
    container_name: catalog-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: commerce-catalog
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin1234
    ports:
      - "3304:3306"
    volumes:
      - ./catalog_mariadb_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: catalog-service:latest
    container_name: catalog-service
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/commerce-catalog
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin1234
      SPRING_KAFKA_BOOTSTRAP_SERVERS: host.docker.internal:9092
    ports:
      - "8084:8084"
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health/liveness"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 60s
