kafka:
  topics:
    product-created: koosco.commerce.dev.product.created
    sku-created: koosco.commerce.dev.sku.created

logging:
  level:
    org.flywaydb: info
    org.hibernate.SQL: info
    org.hibernate.orm.jdbc.bind: warn
